import { Trash2, Printer, Download } from "lucide-react";
import { type InventoryItem, calculateTotalWeight, calculateTotalCubicFeet, DENSITY_FACTOR } from "@/lib/priceCalculator";
import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface InventoryTableProps {
  items: InventoryItem[];
  onUpdateItem: (id: string, updates: Partial<InventoryItem>) => void;
  onRemoveItem: (id: string) => void;
  onClear: () => void;
}

// Helper to get cubic feet for an item
const getItemCubicFeet = (item: InventoryItem): number => {
  return item.cubicFeet || Math.ceil(item.weightEach / DENSITY_FACTOR);
};

export default function InventoryTable({ items, onUpdateItem, onRemoveItem, onClear }: InventoryTableProps) {
  const totalWeight = calculateTotalWeight(items);
  const totalCubicFeet = calculateTotalCubicFeet(items);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const currentDate = format(new Date(), "MMMM d, yyyy");
    
    // Header - Match print styling exactly
    // Green header bar
    doc.setFillColor(34, 197, 94); // Primary green
    doc.rect(0, 0, pageWidth, 25, 'F');
    
    // Logo text
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("TruMove", 14, 16);
    
    // Date on right
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated: ${currentDate}`, pageWidth - 14, 16, { align: "right" });
    
    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Your Move Inventory", 14, 40);
    
    // Item count
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`${items.length} items added`, 14, 48);
    
    // Table data - matching print columns exactly
    const tableData = items.map(item => {
      const cubicFt = getItemCubicFeet(item);
      return [
        item.name,
        item.room,
        item.quantity.toString(),
        `${item.weightEach}`,
        `${cubicFt}`,
        `${item.quantity * item.weightEach}`,
        `${item.quantity * cubicFt}`
      ];
    });
    
    // Add table with print-matching styling
    autoTable(doc, {
      startY: 55,
      head: [['Item', 'Room', 'Qty', 'Weight (lbs)', 'Cu Ft', 'Total Weight', 'Total Cu Ft']],
      body: tableData,
      foot: [[
        '', '', 'Totals:', '—', '—', 
        `${totalWeight.toLocaleString()} lbs`, 
        `${totalCubicFeet} cu ft`
      ]],
      headStyles: {
        fillColor: [34, 197, 94],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
        cellPadding: 4,
      },
      footStyles: {
        fillColor: [245, 245, 245],
        textColor: [0, 0, 0],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        cellPadding: 4,
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250]
      },
      columnStyles: {
        0: { cellWidth: 50 }, // Item
        1: { cellWidth: 35 }, // Room
        2: { cellWidth: 15, halign: 'center' }, // Qty
        3: { cellWidth: 25, halign: 'center' }, // Weight
        4: { cellWidth: 20, halign: 'center' }, // Cu Ft
        5: { cellWidth: 28, halign: 'center' }, // Total Weight
        6: { cellWidth: 25, halign: 'center' }, // Total Cu Ft
      },
      styles: {
        overflow: 'linebreak',
        lineColor: [230, 230, 230],
        lineWidth: 0.5,
      },
      tableLineColor: [200, 200, 200],
      tableLineWidth: 0.5,
    });
    
    // Footer - matching print footer
    const finalY = (doc as any).lastAutoTable.finalY || 100;
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text("Generated by TruMove - AI-powered moving quotes", 14, finalY + 12);
    doc.text("www.trumove.com", 14, finalY + 18);
    
    doc.save('trumove-inventory.pdf');
  };

  const currentDate = format(new Date(), "MMMM d, yyyy");

  return (
    <div className="print-inventory rounded-xl border border-border/60 bg-card shadow-sm overflow-hidden">
      {/* Print-only header with logo and date */}
      <div className="print-header hidden">
        <div className="print-header-content">
          <div className="print-logo">TruMove</div>
          <div className="print-date">Generated: {currentDate}</div>
        </div>
      </div>
      
      {/* Header - Enlarged and Centered */}
      <div className="tru-summary-header-large border-b border-border/40">
        <div className="text-center flex-1">
          <h3 className="text-lg font-black text-foreground">
            Your Move <span className="tru-qb-title-accent">Inventory</span>
          </h3>
          <p className="text-[10px] text-muted-foreground uppercase tracking-wide">{items.length} items added</p>
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border/40 bg-muted/30">
              <th className="text-left px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Item</th>
              <th className="text-left px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Room</th>
              <th className="text-center px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Qty</th>
              <th className="text-center px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Weight (lbs)</th>
              <th className="text-center px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Cu Ft</th>
              <th className="text-center px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Total Weight</th>
              <th className="text-center px-4 py-3 font-bold text-xs tracking-wide uppercase text-muted-foreground">Total Cu Ft</th>
              <th className="w-12 print-hide"></th>
            </tr>
          </thead>
          <tbody>
            {items.length === 0 ? (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-muted-foreground">
                  No items yet. Start by adding a sofa, bed, or boxes.
                </td>
              </tr>
            ) : (
              items.map((item) => {
                const cubicFt = getItemCubicFeet(item);
                return (
                  <tr key={item.id} className="border-b border-border/20 hover:bg-muted/20 transition-colors">
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-3">
                        {/* Larger thumbnail */}
                        <div className="w-10 h-10 flex-shrink-0 rounded-lg overflow-hidden bg-muted/30 border border-border/30">
                          {item.imageUrl ? (
                            <img 
                              src={item.imageUrl} 
                              alt={item.name} 
                              className="w-full h-full object-contain p-0.5"
                            />
                          ) : (
                            <div className="w-full h-full flex items-center justify-center">
                              <span className="text-base text-muted-foreground">📦</span>
                            </div>
                          )}
                        </div>
                        <span className="font-medium text-foreground">{item.name}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3 text-muted-foreground">{item.room}</td>
                    <td className="px-4 py-3 text-center">
                      {/* Hidden span for print, input for screen */}
                      <span className="print-qty-value hidden">{item.quantity}</span>
                      <input
                        type="number"
                        min={1}
                        value={item.quantity}
                        onChange={(e) => onUpdateItem(item.id, { quantity: Math.max(1, parseInt(e.target.value) || 1) })}
                        className="w-14 h-8 text-center rounded-lg border border-border/40 bg-background text-sm font-medium focus:outline-none focus:ring-2 focus:ring-primary/20"
                      />
                    </td>
                    <td className="px-4 py-3 text-center text-muted-foreground">
                      {item.weightEach}
                    </td>
                    <td className="px-4 py-3 text-center text-muted-foreground">
                      {cubicFt}
                    </td>
                    <td className="px-4 py-3 text-center font-semibold">
                      {item.quantity * item.weightEach}
                    </td>
                    <td className="px-4 py-3 text-center font-semibold">
                      {item.quantity * cubicFt}
                    </td>
                    <td className="px-4 py-3 text-center print-hide">
                      <button
                        type="button"
                        onClick={() => onRemoveItem(item.id)}
                        className="p-1.5 rounded-lg text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors"
                        aria-label="Remove item"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
          {/* Table Footer with Totals */}
          {items.length > 0 && (
            <tfoot>
              <tr className="border-t border-border/40 bg-muted/20 font-bold">
                <td colSpan={3} className="px-4 py-3 text-right text-sm text-muted-foreground">Totals:</td>
                <td className="px-4 py-3 text-center text-sm">—</td>
                <td className="px-4 py-3 text-center text-sm">—</td>
                <td className="px-4 py-3 text-center text-sm text-foreground">{totalWeight.toLocaleString()} lbs</td>
                <td className="px-4 py-3 text-center text-sm text-foreground">{totalCubicFeet} cu ft</td>
                <td className="print-hide"></td>
              </tr>
            </tfoot>
          )}
        </table>
      </div>

      {/* Actions - Hidden in print */}
      <div className="print-actions p-4 border-t border-border/40 flex flex-wrap gap-3">
        <button
          type="button"
          onClick={handlePrint}
          disabled={items.length === 0}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-border/60 bg-card text-sm font-semibold text-foreground hover:bg-muted/50 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Printer className="w-4 h-4" />
          Print inventory
        </button>
        <button
          type="button"
          onClick={handleDownloadPDF}
          disabled={items.length === 0}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-border/60 bg-card text-sm font-semibold text-foreground hover:bg-muted/50 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Download className="w-4 h-4" />
          Download as PDF
        </button>
        {items.length > 0 && (
          <button
            type="button"
            onClick={onClear}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-destructive hover:bg-destructive/10 transition-all"
          >
            <Trash2 className="w-4 h-4" />
            Clear all
          </button>
        )}
      </div>
    </div>
  );
}
