import { useState, useCallback } from "react";
import SiteShell from "@/components/layout/SiteShell";
import InventoryBuilder from "@/components/estimate/InventoryBuilder";
import InventoryTable from "@/components/estimate/InventoryTable";
import QuoteSnapshot from "@/components/estimate/QuoteSnapshot";
import MoveDetailsForm from "@/components/estimate/MoveDetailsForm";
import InventoryIntroModal from "@/components/estimate/InventoryIntroModal";
import { type InventoryItem, type MoveDetails, calculateTotalWeight, formatCurrency, calculateEstimate } from "@/lib/priceCalculator";

export default function OnlineEstimate() {
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [inventoryUnlocked, setInventoryUnlocked] = useState(false);
  const [showIntroModal, setShowIntroModal] = useState(false);
const [moveDetails, setMoveDetails] = useState<MoveDetails>({
    fromLocation: '',
    toLocation: '',
    distance: 0,
    moveType: 'auto',
    moveDate: '',
    homeSize: '' as MoveDetails['homeSize'],
  });
  const [contactInfo, setContactInfo] = useState({
    name: '',
    email: '',
    phone: '',
  });

  const handleAddItem = useCallback((item: Omit<InventoryItem, 'id'>) => {
    const newItem: InventoryItem = {
      ...item,
      id: crypto.randomUUID(),
    };
    setItems(prev => [...prev, newItem]);
  }, []);

  const handleUpdateItem = useCallback((id: string, updates: Partial<InventoryItem>) => {
    setItems(prev => prev.map(item => 
      item.id === id ? { ...item, ...updates } : item
    ));
  }, []);

  const handleRemoveItem = useCallback((id: string) => {
    setItems(prev => prev.filter(item => item.id !== id));
  }, []);

  const handleClearAll = useCallback(() => {
    setItems([]);
  }, []);

  const handleProceedToInventory = () => {
    setShowIntroModal(true);
  };

  const handleCloseModal = () => {
    setShowIntroModal(false);
    setInventoryUnlocked(true);
  };

  const handleSubmit = () => {
    const totalWeight = calculateTotalWeight(items);
    const effectiveMoveType = moveDetails.moveType === 'auto' 
      ? (moveDetails.distance >= 150 ? 'long-distance' : 'local')
      : moveDetails.moveType;
    const estimate = calculateEstimate(totalWeight, moveDetails.distance, effectiveMoveType);
    
    const inventoryList = items.map(item => 
      `• ${item.name} (${item.room}) - Qty: ${item.quantity}, Weight: ${item.quantity * item.weightEach} lbs`
    ).join('\n');

    const subject = encodeURIComponent(`TruMove Quote Request - ${contactInfo.name}`);
    const body = encodeURIComponent(`
TruMove Moving Quote Request

CONTACT INFORMATION
Name: ${contactInfo.name}
Email: ${contactInfo.email}
Phone: ${contactInfo.phone}

MOVE DETAILS
From: ${moveDetails.fromLocation}
To: ${moveDetails.toLocation}
Distance: ${moveDetails.distance} miles
Move Type: ${effectiveMoveType}
Target Date: ${moveDetails.moveDate}

INVENTORY (${items.length} items, ${totalWeight.toLocaleString()} lbs total)
${inventoryList}

ESTIMATED RANGE: ${formatCurrency(estimate.min)} - ${formatCurrency(estimate.max)}

---
Generated by TruMove Online Estimate Tool
    `.trim());

    window.location.href = `mailto:quotes@trumove.com?subject=${subject}&body=${body}`;
  };

  return (
    <SiteShell>
      <div className="max-w-[1400px] mx-auto px-4 py-8">
        {/* Compact Hero */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-border/60 bg-card shadow-sm mb-4">
            <span className="w-1.5 h-1.5 rounded-full bg-primary" />
            <span className="text-[9px] font-black tracking-[0.16em] uppercase text-muted-foreground">
              AI-Powered Moving Estimate
            </span>
          </div>
          <h1 className="text-3xl md:text-4xl font-black tracking-tight text-foreground mb-2">
            Get your instant moving quote
          </h1>
          <p className="text-sm text-muted-foreground max-w-xl mx-auto">
            Enter your route, build your inventory, and get a live price estimate.
          </p>
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] gap-6">
          {/* Left Column - Forms */}
          <div className="space-y-6">
            {/* Step 1 - Route & Details */}
            <section className="rounded-2xl border border-border/60 bg-card p-5 shadow-lg">
              <div className="flex items-center gap-2 mb-4">
                <span className="w-7 h-7 rounded-full bg-primary text-primary-foreground text-sm font-bold flex items-center justify-center">1</span>
                <h2 className="text-lg font-black text-foreground">Your move details</h2>
              </div>
              <MoveDetailsForm
                moveDetails={moveDetails}
                onUpdate={(updates) => setMoveDetails(prev => ({ ...prev, ...updates }))}
                onProceed={handleProceedToInventory}
              />
            </section>

            {/* Step 2 - Inventory */}
            <section className={`rounded-2xl border border-border/60 bg-card p-5 shadow-lg transition-all duration-300 ${
              !inventoryUnlocked ? 'opacity-50 pointer-events-none' : ''
            }`}>
              <div className="flex items-center gap-2 mb-4">
                <span className={`w-7 h-7 rounded-full text-sm font-bold flex items-center justify-center ${
                  inventoryUnlocked 
                    ? 'bg-primary text-primary-foreground' 
                    : 'bg-muted text-muted-foreground'
                }`}>2</span>
                <h2 className="text-lg font-black text-foreground">Build your inventory</h2>
                {!inventoryUnlocked && (
                  <span className="text-xs text-muted-foreground ml-auto">Complete step 1 first</span>
                )}
              </div>
              <InventoryBuilder onAddItem={handleAddItem} />
            </section>

            {/* Inventory Table */}
            {items.length > 0 && (
              <InventoryTable 
                items={items}
                onUpdateItem={handleUpdateItem}
                onRemoveItem={handleRemoveItem}
                onClear={handleClearAll}
              />
            )}

            {/* Finalize Section - Shows after inventory is unlocked and has items */}
            {inventoryUnlocked && items.length > 0 && (
              <section className="rounded-2xl border border-border/60 bg-card p-5 shadow-lg">
                <div className="flex items-center gap-2 mb-4">
                  <span className="w-7 h-7 rounded-full bg-primary text-primary-foreground text-sm font-bold flex items-center justify-center">3</span>
                  <h2 className="text-lg font-black text-foreground">Finalize your estimate</h2>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-4">
                  <input
                    type="text"
                    value={contactInfo.name}
                    onChange={(e) => setContactInfo(prev => ({ ...prev, name: e.target.value }))}
                    placeholder="Full name"
                    className="h-10 px-3 rounded-lg border border-border/60 bg-background text-sm placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40"
                  />
                  <input
                    type="email"
                    value={contactInfo.email}
                    onChange={(e) => setContactInfo(prev => ({ ...prev, email: e.target.value }))}
                    placeholder="Email"
                    className="h-10 px-3 rounded-lg border border-border/60 bg-background text-sm placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40"
                  />
                  <input
                    type="tel"
                    value={contactInfo.phone}
                    onChange={(e) => setContactInfo(prev => ({ ...prev, phone: e.target.value }))}
                    placeholder="Phone"
                    className="h-10 px-3 rounded-lg border border-border/60 bg-background text-sm placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/40"
                  />
                </div>
                <button
                  type="button"
                  onClick={handleSubmit}
                  className="w-full h-11 rounded-lg bg-primary text-primary-foreground text-sm font-bold tracking-wide uppercase transition-all hover:-translate-y-0.5 hover:shadow-lg flex items-center justify-center gap-2"
                >
                  Finalize My Estimate →
                </button>
              </section>
            )}
          </div>

          {/* Right Column - Quote Snapshot */}
          <div className="lg:sticky lg:top-[100px] lg:self-start">
            <QuoteSnapshot items={items} moveDetails={moveDetails} />
          </div>
        </div>
      </div>

      {/* Intro Modal */}
      <InventoryIntroModal
        isOpen={showIntroModal}
        onClose={handleCloseModal}
        distance={moveDetails.distance}
        moveType={moveDetails.moveType}
      />
    </SiteShell>
  );
}