import { useState, useCallback } from "react";
import SiteShell from "@/components/layout/SiteShell";
import InventoryBuilder from "@/components/estimate/InventoryBuilder";
import InventoryTable from "@/components/estimate/InventoryTable";
import QuoteSnapshot from "@/components/estimate/QuoteSnapshot";
import MoveDetailsForm from "@/components/estimate/MoveDetailsForm";
import { type InventoryItem, type MoveDetails, calculateTotalWeight, formatCurrency, calculateEstimate } from "@/lib/priceCalculator";
import { CheckCircle2 } from "lucide-react";

export default function OnlineEstimate() {
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [moveDetails, setMoveDetails] = useState<MoveDetails>({
    fromLocation: '',
    toLocation: '',
    distance: 0,
    moveType: 'auto',
    moveDate: '',
  });
  const [contactInfo, setContactInfo] = useState({
    name: '',
    email: '',
    phone: '',
  });

  const handleAddItem = useCallback((item: Omit<InventoryItem, 'id'>) => {
    const newItem: InventoryItem = {
      ...item,
      id: crypto.randomUUID(),
    };
    setItems(prev => [...prev, newItem]);
  }, []);

  const handleUpdateItem = useCallback((id: string, updates: Partial<InventoryItem>) => {
    setItems(prev => prev.map(item => 
      item.id === id ? { ...item, ...updates } : item
    ));
  }, []);

  const handleRemoveItem = useCallback((id: string) => {
    setItems(prev => prev.filter(item => item.id !== id));
  }, []);

  const handleClearAll = useCallback(() => {
    setItems([]);
  }, []);

  const handleSubmit = () => {
    const totalWeight = calculateTotalWeight(items);
    const effectiveMoveType = moveDetails.moveType === 'auto' 
      ? (moveDetails.distance >= 150 ? 'long-distance' : 'local')
      : moveDetails.moveType;
    const estimate = calculateEstimate(totalWeight, moveDetails.distance, effectiveMoveType);
    
    const inventoryList = items.map(item => 
      `• ${item.name} (${item.room}) - Qty: ${item.quantity}, Weight: ${item.quantity * item.weightEach} lbs`
    ).join('\n');

    const subject = encodeURIComponent(`TruMove Quote Request - ${contactInfo.name}`);
    const body = encodeURIComponent(`
TruMove Moving Quote Request

CONTACT INFORMATION
Name: ${contactInfo.name}
Email: ${contactInfo.email}
Phone: ${contactInfo.phone}

MOVE DETAILS
From: ${moveDetails.fromLocation}
To: ${moveDetails.toLocation}
Distance: ${moveDetails.distance} miles
Move Type: ${effectiveMoveType}
Target Date: ${moveDetails.moveDate}

INVENTORY (${items.length} items, ${totalWeight.toLocaleString()} lbs total)
${inventoryList}

ESTIMATED RANGE: ${formatCurrency(estimate.min)} - ${formatCurrency(estimate.max)}

---
Generated by TruMove Online Estimate Tool
    `.trim());

    window.location.href = `mailto:quotes@trumove.com?subject=${subject}&body=${body}`;
  };

  return (
    <SiteShell>
      <div className="max-w-[1480px] mx-auto px-6 py-12">
        {/* Hero */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-border/60 bg-card shadow-sm mb-6">
            <span className="w-2 h-2 rounded-full bg-primary shadow-[0_0_0_4px_hsl(var(--primary)/0.18)]" />
            <span className="text-[10px] font-black tracking-[0.16em] uppercase text-muted-foreground">
              Instant Moving Quote Powered by TruMove AI
            </span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight text-foreground mb-4">
            Build your inventory, then let TruMove calculate a live estimate.
          </h1>
          <p className="text-lg text-muted-foreground max-w-3xl mx-auto mb-6">
            Start with a simple inventory so TruMove can estimate your total weight and move size. Then add your route and date to see a live price range and lock in a call or video consult.
          </p>
          
          {/* Steps */}
          <div className="flex flex-wrap justify-center gap-6 mb-8">
            <div className="flex items-center gap-3">
              <span className="w-8 h-8 rounded-full bg-foreground text-background text-sm font-bold flex items-center justify-center">1</span>
              <span className="text-sm font-semibold text-foreground">Build your inventory list</span>
            </div>
            <div className="flex items-center gap-3">
              <span className="w-8 h-8 rounded-full bg-foreground text-background text-sm font-bold flex items-center justify-center">2</span>
              <span className="text-sm font-semibold text-foreground">Get your estimate and schedule</span>
            </div>
          </div>

          {/* What You Get */}
          <div className="flex flex-wrap justify-center gap-4">
            {[
              'Weight and size estimate based on your items',
              'Smart pricing that adjusts to distance and load',
              'Option to book a video walkthrough or call',
            ].map((item) => (
              <div key={item} className="flex items-center gap-2 px-3 py-2 rounded-xl bg-muted/50 text-sm font-medium text-foreground/80">
                <CheckCircle2 className="w-4 h-4 text-primary" />
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_380px] gap-8">
          {/* Left Column - Forms */}
          <div className="space-y-10">
            {/* Step 1 */}
            <section>
              <div className="flex items-center gap-3 mb-6">
                <span className="w-10 h-10 rounded-full bg-primary text-primary-foreground text-lg font-bold flex items-center justify-center shadow-[0_0_0_4px_hsl(var(--primary)/0.18)]">1</span>
                <h2 className="text-2xl font-black text-foreground">Build your inventory list</h2>
              </div>
              
              <div className="rounded-2xl border border-border/60 bg-card p-6 shadow-lg">
                <div className="mb-6">
                  <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-muted/60 text-[9px] font-black tracking-[0.2em] uppercase text-muted-foreground mb-2">
                    TruMove AI • Weight and Size Estimate
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Start with quick add items by room, then add anything custom. TruMove will estimate your total weight and move size, then use it in your quote below.
                  </p>
                </div>
                
                <InventoryBuilder onAddItem={handleAddItem} />
              </div>

              <div className="mt-6">
                <InventoryTable 
                  items={items}
                  onUpdateItem={handleUpdateItem}
                  onRemoveItem={handleRemoveItem}
                  onClear={handleClearAll}
                />
              </div>
            </section>

            {/* Step 2 */}
            <section>
              <div className="flex items-center gap-3 mb-6">
                <span className="w-10 h-10 rounded-full bg-primary text-primary-foreground text-lg font-bold flex items-center justify-center shadow-[0_0_0_4px_hsl(var(--primary)/0.18)]">2</span>
                <h2 className="text-2xl font-black text-foreground">Get your AI powered quote and schedule</h2>
              </div>
              
              <div className="rounded-2xl border border-border/60 bg-card p-6 shadow-lg">
                <MoveDetailsForm
                  moveDetails={moveDetails}
                  onUpdate={(updates) => setMoveDetails(prev => ({ ...prev, ...updates }))}
                  contactInfo={contactInfo}
                  onContactUpdate={(updates) => setContactInfo(prev => ({ ...prev, ...updates }))}
                  onSubmit={handleSubmit}
                />
              </div>
            </section>
          </div>

          {/* Right Column - Quote Snapshot */}
          <div className="lg:sticky lg:top-[120px] lg:self-start">
            <QuoteSnapshot items={items} moveDetails={moveDetails} />
          </div>
        </div>
      </div>
    </SiteShell>
  );
}
